export const environment = {
  production: true,
  googleClientId: '120661807938-2evmi1g6q6n0i5ssfe23tbl8dd00mhau.apps.googleusercontent.com',
  microsoftClientId: '5a443317-5785-48ef-827d-012ab62f8319',
  kipuApiHost: 'https://kipu-api-os.duckdns.org',
  kipuApiBaseUrl: 'https://kipu-api-os.duckdns.org/api/v1',
  kipuApiInventoryMaterialsEndpointPath: '/materials/inventory',
  kipuApiMaterialsEndpointPath: '/materials',
  kipuApiRequestEndpointPath: '/materials/requests',
  kipuApiMachineryEndpointPath: '/machinery',
  kipuApiTeamEndpointPath: '/team',
  kipuApiTeamUsersEndpointPath: '/users',
  kipuApiInvitationsEndpointPath: '/invitations',
  kipuApiTeamWorkersEndpointPath: '/team-workers',
  kipuApiSuppliersEndpointPath: '/materials/suppliers',
  kipuApiWasteEndpointPath: '/materials/waste',
  kipuApiCategoriesEndPath: '/materials/categories',
  kipuApiDocumentsEndpointPath: '/documents',
  kipuApiIoTMonitoringEndpointPath: '/iot-monitoring',
  kipuApiSupplierOfferEndPath: '/materials/supplierOffer',
  kipuApiConcreteCuringEndpointPath: '/concreteCuring',
  kipuApiGeolocalizationEndpointPath: '/geolocalization',
  kipuApiHopperWatchEndpointPath: '/hopperWatch',
  kipuApiSeismicControlEndpointPath: '/seismicControl',
  kipuApiProjectsEndpointPath: '/projects',
  kipuApiBudgetEndpointPath: '/budgets',
};
