export const environment = {
  production: false,
  googleClientId: '120661807938-2evmi1g6q6n0i5ssfe23tbl8dd00mhau.apps.googleusercontent.com',
  microsoftClientId: '5a443317-5785-48ef-827d-012ab62f8319',
  kipuApiBaseUrl: '/api/v1',
  kipuApiHost: 'http://localhost:3000',
  kipuApiHostLocal: 'http://localhost:8080/api/v1',
  kipuApiInventoryMaterialsEndpointPath: '/material-inventories',
  kipuApiMaterialsEndpointPath: '/material-catalogs',
  kipuApiRequestEndpointPath: '/material-requests',
  kipuApiProjectsEndpointPath: '/projects',
  kipuApiMachineryEndpointPath: '/machinery',
  kipuApiTeamEndpointPath: '/team',
  kipuApiTeamUsersEndpointPath: '/team-users',
  kipuApiTeamWorkersEndpointPath: '/team-workers',
  kipuApiSuppliersEndpointPath: '/suppliers',
  kipuApiWasteEndpointPath: '/materials/waste',
  kipuApiCategoriesEndPath: '/material-categories',
  kipuApiDocumentsEndpointPath: '/documents',
  kipuApiSupplierOfferEndPath: '/supplier-offers',
  kipuApiIoTMonitoringEndpointPath: '/iot-monitoring',
  kipuApiConcreteCuringEndpointPath: '/concrete-curing-sensors',
  kipuApiGeolocalizationEndpointPath: '/geolocalization-sensors',
  kipuApiHopperWatchEndpointPath: '/hopper-watches',
  kipuApiSeismicControlEndpointPath: '/seismic-control-sensors',
  kipuApiBudgetEndpointPath: '/budgets',
};
