export const environment = {
  production: false,
  kipuApiHost: 'http://localhost:3000',
  kipuApiBaseUrl: '/api/v1',
  kipuApiInventoryMaterialsEndpointPath: '/materials/inventory',
  kipuApiMaterialsEndpointPath: '/materials',
  kipuApiRequestEndpointPath: '/materials/requests',
  kipuApiMachineryEndpointPath: '/machinery',
  kipuApiTeamEndpointPath: '/team',
  kipuApiTeamUsersEndpointPath: '/team-users',
  kipuApiTeamWorkersEndpointPath: '/team-workers',
  kipuApiSuppliersEndpointPath: '/materials/suppliers',
  kipuApiWasteEndpointPath: '/materials/waste',
  kipuApiCategoriesEndPath: '/materials/categories',
  kipuApiDocumentsEndpointPath: '/documents',
  kipuApiIoTMonitoringEndpointPath: '/iot-monitoring',
  kipuApiSupplierOfferEndPath: '/materials/supplierOffer',
  kipuApiConcreteCuringEndpointPath: '/concrete-curing',
  kipuApiGeolocalizationEndpointPath: '/geolocalization',
  kipuApiHopperWatchEndpointPath: '/hopper-watch',
  kipuApiSeismicControlEndpointPath: '/seismic-control',
  kipuApiProjectsEndpointPath: '/projects',
};
